### ISSUE TITLE
tox will break when tox4 will be released

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.PythonScripts#48]
I tried to run tox all Zope and Plone repos this weekend, see https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/

tox for this repo will break when tox4 will be released.

```
❯ tox4 -e py38
py38: commands[0]> .tox/4/py38/bin/buildout -c /home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/buildout.cfg buildout:directory=/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38 buildout:develop=/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts bootstrap
Creating directory '/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/develop-eggs'.
py38: commands[1]> .tox/4/py38/bin/buildout -c /home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/buildout.cfg buildout:directory=/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38 buildout:develop=/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts install test
Develop: '/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
Getting distribution for 'zc.recipe.egg==2.0.7'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'main' from 'setuptools.command.easy_install' (/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py)
An error occurred when trying to install /tmp/tmp8r13rnl4get_dist/zc.recipe.egg-2.0.7.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section test.
  Initializing section test.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zc.recipe.egg==2.0.7'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1324, in __getitem__
    options._initialize()
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1432, in _initialize
    self.initialize()
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1438, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1381, in _install_and_load
    zc.buildout.easy_install.install(
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
py38: exit 1 (1.26 seconds) /home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts> .tox/4/py38/bin/buildout -c /home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/buildout.cfg buildout:directory=/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts/.tox/4/py38 buildout:develop=/home/jugmac00/All/output_zope/zopefoundation/Products.PythonScripts install test pid=9385
  py38: FAIL code 1 (1.89=setup[0.04]+cmd[0.59,1.26] seconds)
  evaluation failed :( (1.92 seconds)
```

The reason is that tox4 will use `isolated builds` by default, and thus pull in a too new `setuptools` version.

We need to pin `setuptools` to < 52, see https://github.com/buildout/buildout/issues/543

Maybe it would be a good idea to migrate this repo to use GHA first.

I tried to use meta/config tool today, and I am not sure how to use it - I created two issues over there.

**Comment by jugmac00** [comment]
Thank you!
